"""init

Revision ID: 0d3d3e16d925
Revises: 921192ec0749
Create Date: 2021-01-12 11:14:24.657398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d3d3e16d925'
down_revision = '921192ec0749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('sid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_table('users')
    op.drop_table('user_session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_session',
    sa.Column('user_session_cookie', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_session_email', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=300), nullable=True),
    sa.Column('Input_parameters', mysql.LONGBLOB(), nullable=True),
    sa.Column('user_results', mysql.LONGBLOB(), nullable=True),
    sa.ForeignKeyConstraint(['user_session_email'], ['users.emailaddress'], name='user_session_ibfk_1'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('emailaddress', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=250), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=250), nullable=False),
    sa.PrimaryKeyConstraint('emailaddress'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
