"""init

Revision ID: 78f140072d24
Revises: 0d3d3e16d925
Create Date: 2021-03-08 15:51:08.042677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f140072d24'
down_revision = '0d3d3e16d925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('user_sid', sa.String(length=64), nullable=False),
    sa.Column('datetime_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sim_id', sa.String(length=64), nullable=True),
    sa.Column('sim_cfg_blob', sa.LargeBinary(), nullable=True),
    sa.Column('sim_inp_blob', sa.LargeBinary(), nullable=True),
    sa.Column('sim_out_blob', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_sim_id'), 'simulation', ['sim_id'], unique=False)
    op.create_index(op.f('ix_simulation_user_sid'), 'simulation', ['user_sid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_user_sid'), table_name='simulation')
    op.drop_index(op.f('ix_simulation_sim_id'), table_name='simulation')
    op.drop_table('simulation')
    # ### end Alembic commands ###
