longname = {'S':  'Susceptible',
            'E':  'Exposed',
            'I':  'Infected (symptomatic)',
            'A':  'Asymptomatically Infected',
            'R':  'Recovered',
            'H':  'Hospitalised',
            'C':  'Critical',
            'D':  'Deaths',
            'O':  'Offsite',
            'Q':  'Quarantined',
            'U':  'No ICU Care',
            'CS': 'Change in Susceptible',
            'CE': 'Change in Exposed',
            'CI': 'Change in Infected (symptomatic)',
            'CA': 'Change in Asymptomatically Infected',
            'CR': 'Change in Recovered',
            'CH': 'Change in Hospitalised',
            'CC': 'Change in Critical',
            'CD': 'Change in Deaths',
            'CO': 'Change in Offsite',
            'CQ': 'Change in Quarantined',
            'CU': 'Change in No ICU Care',
            'Ninf': 'Change in total active infections', # sum of E, I, A
}


shortname = {'S':  'Sus.',
             'E':  'Exp.',
             'I':  'Inf. (symp.)',
             'A':  'Asym.',
             'R':  'Rec.',
             'H':  'Hosp.',
             'C':  'Crit.',
             'D':  'Deaths',
             'O':  'Offsite',
             'Q':  'Quar.',
             'U':  'No ICU',
             'CS': 'Change in Sus.',
             'CE': 'Change in Exp.',
             'CI': 'Change in Inf. (symp.)',
             'CA': 'Change in Asym.',
             'CR': 'Change in Rec.',
             'CH': 'Change in Hosp.',
             'CC': 'Change in Crit.',
             'CD': 'Change in Deaths',
             'CO': 'Change in Offsite',
             'CQ': 'Change in Quar.',
             'CU':  'Change in No ICU',
             'Ninf': 'New Infected', # newly exposed to the disease = - change in susceptibles
}


index = {'S': 0,
        'E':  1,
        'I':  2,
        'A':  3,
        'R':  4,
        'H':  5,
        'C':  6,
        'D':  7,
        'O':  8,
        'Q':  9,
        'U':  10,
        'CS': 11,
        'CE': 12,
        'CI': 13,
        'CA': 14,
        'CR': 15,
        'CH': 16,
        'CC': 17,
        'CD': 18,
        'CO': 19,
        'CQ': 20,
        'CU': 21,
        'Ninf': 22,
        }


# This is for the plotter and will be deprecated soon
colour = {'S':  'rgb(0,0,255)', #'blue',
          'E':  'rgb(255,150,255)', #'pink',
          'I':  'rgb(255,150,50)', #'orange',
          'A':  'rgb(255,50,50)', #'dunno',
          'R':  'rgb(0,255,0)', #'green',
          'H':  'rgb(255,0,0)', #'red',
          'C':  'rgb(50,50,50)', #'black',
          'D':  'rgb(130,0,255)', #'purple',
          'O':  'rgb(130,100,150)', #'dunno',
          'Q':  'rgb(150,130,100)', #'dunno',
          'U':  'rgb(150,100,150)', #'dunno',
          'CS': 'rgb(0,0,255)', #'blue',
          'CE': 'rgb(255,150,255)', #'pink',
          'CI': 'rgb(255,150,50)', #'orange',
          'CA': 'rgb(255,50,50)', #'dunno',
          'CR': 'rgb(0,255,0)', #'green',
          'CH': 'rgb(255,0,0)', #'red',
          'CC': 'rgb(50,50,50)', #'black',
          'CD': 'rgb(130,0,255)', #'purple',
          'CO': 'rgb(130,100,150)', #'dunno',
          'CQ': 'rgb(150,130,100)', #'dunno',
          'CU':  'rgb(150,100,150)', #'dunno',
          'Ninf': 'rgb(255,125,100)', #
        }


# This is for the plotter and will be deprecated soon
fill_colour = {'S':  'rgba(0,0,255),0.1', #'blue',
          'E':  'rgba(255,150,255),0.1', #'pink',
          'I':  'rgba(255,150,50),0.1', #'orange',
          'A':  'rgba(255,50,50),0.1', #'dunno',
          'R':  'rgba(0,255,0),0.1', #'green',
          'H':  'rgba(255,0,0),0.1', #'red',
          'C':  'rgba(50,50,50),0.1', #'black',
          'D':  'rgba(130,0,255),0.1', #'purple',
          'O':  'rgba(130,100,150),0.1', #'dunno',
          'Q':  'rgba(150,130,100),0.1', #'dunno',
          'U':  'rgba(150,100,150),0.1', #'dunno',
          'CS': 'rgba(0,0,255),0.1', #'blue',
          'CE': 'rgba(255,150,255),0.1', #'pink',
          'CI': 'rgba(255,150,50),0.1', #'orange',
          'CA': 'rgba(255,50,50),0.1', #'dunno',
          'CR': 'rgba(0,255,0),0.1', #'green',
          'CH': 'rgba(255,0,0),0.1', #'red',
          'CC': 'rgba(50,50,50),0.1', #'black',
          'CD': 'rgba(130,0,255),0.1', #'purple',
          'CO': 'rgba(130,100,150),0.1', #'dunno',
          'CQ': 'rgba(150,130,100),0.1', #'dunno',
          'CU':  'rgba(150,100,150),0.1', #'dunno',
          'Ninf': 'rgba(255,125,100),0.1', #
        }