countries_map = {
    'Albania': 'Albania.csv',
    'Algeria': 'Algeria.csv',
    'Andorra': 'Andorra.csv',
    'Antigua and Barbuda': 'Antigua and Barbuda.csv',
    'Argentina': 'Argentina.csv',
    'Armenia': 'Armenia.csv',
    'Australia': 'Australia.csv',
    'Austria': 'Austria.csv',
    'Azerbaijan': 'Azerbaijan.csv',
    'Bahama': 'Bahamas.csv',
    'Bahrain': 'Bahrain.csv',
    'Bangladesh': 'Bangladesh.csv',
    'Belarus': 'Belarus.csv',
    'Belgium': 'Belgium.csv',
    'Belize': 'Belize.csv',
    'Benin': 'Benin.csv',
    'Bhutan': 'Bhutan.csv',
    'Bolivia': 'Bolivia.csv',
    'Bosnia and Herzegovina': 'Bosnia and Herzegovina.csv',
    'Botswana': 'Botswana.csv',
    'Brazil': 'Brazil.csv',
    'Brunei': 'Brunei Darussalam.csv',
    'Bulgaria': 'Bulgaria.csv',
    'Burkina Faso': 'Burkina Faso.csv',
    'Cabo Verde': 'Cabo Verde.csv',
    'Cambodia': 'Cambodia.csv',
    'Cameroon': 'Cameroon.csv',
    'Canada': 'Canada.csv',
    'Chile': 'Chile.csv',
    'China': 'China.csv',
    'Colombia': 'Colombia.csv',
    'Congo': 'Congo.csv',
    'Costa Rica': 'Costa Rica.csv',
    'Croatia': 'Croatia.csv',
    'Cyprus': 'Cyprus.csv',
    'Czech Republic': 'Czech Republic.csv',
    'Denmark': 'Denmark.csv',
    'Dominican Republic': 'Dominican Republic.csv',
    'Ecuador': 'Ecuador.csv',
    'Egypt': 'Egypt.csv',
    'El Salvador': 'El Salvador.csv',
    'Estonia': 'Estonia.csv',
    'Ethiopia': 'Ethiopia.csv',
    'Fiji': 'Fiji.csv',
    'Finland': 'Finland.csv',
    'France': 'France.csv',
    'Georgia': 'Georgia.csv',
    'Germany': 'Germany.csv',
    'Ghana': 'Ghana.csv',
    'Greece': 'Greece.csv',
    'Guatemala': 'Guatemala.csv',
    'Guinea': 'Guinea.csv',
    'Guyana': 'Guyana.csv',
    'Haiti': 'Haiti.csv',
    'Honduras': 'Honduras.csv',
    'Hong Kong SAR': 'Hong Kong SAR, China.csv',
    'Hungary': 'Hungary.csv',
    'Iceland': 'Iceland.csv',
    'India': 'India.csv',
    'Indonesia': 'Indonesia.csv',
    'Iran': 'Iran (Islamic Republic of).csv',
    'Iraq': 'Iraq.csv',
    'Ireland': 'Ireland.csv',
    'Israel': 'Israel.csv',
    'Italy': 'Italy.csv',
    'Jamaica': 'Jamaica.csv',
    'Japan': 'Japan.csv',
    'Jordan': 'Jordan.csv',
    'Kazakhstan': 'Kazakhstan.csv',
    'Kenya': 'Kenya.csv',
    'Kiribati': 'Kiribati.csv',
    'Kuwait': 'Kuwait.csv',
    'Kyrgyzstan': 'Kyrgyzstan.csv',
    "Lao People's Democratic Republic": "Lao People's Democratic Republic.csv",
    'Latvia': 'Latvia.csv',
    'Lebanon': 'Lebanon.csv',
    'Lesotho': 'Lesotho.csv',
    'Liberia': 'Liberia.csv',
    'Lithuania': 'Lithuania.csv',
    'Luxembourg': 'Luxembourg.csv',
    'Malaysia': 'Malaysia.csv',
    'Maldive': 'Maldives.csv',
    'Malta': 'Malta.csv',
    'Mauritania': 'Mauritania.csv',
    'Mauritiu': 'Mauritius.csv',
    'Mexico': 'Mexico.csv',
    'Monaco': 'Monaco.csv',
    'Mongolia': 'Mongolia.csv',
    'Montenegro': 'Montenegro.csv',
    'Morocco': 'Morocco.csv',
    'Mozambique': 'Mozambique.csv',
    'Namibia': 'Namibia.csv',
    'Nepal': 'Nepal.csv',
    'Netherland': 'Netherlands.csv',
    'New Zealand': 'New Zealand.csv',
    'Nicaragua': 'Nicaragua.csv',
    'Niger': 'Niger.csv',
    'Nigeria': 'Nigeria.csv',
    'Oman': 'Oman.csv',
    'Pakistan': 'Pakistan.csv',
    'Panama': 'Panama.csv',
    'Paraguay': 'Paraguay.csv',
    'Peru': 'Peru.csv',
    'Philippine': 'Philippines.csv',
    'Poland': 'Poland.csv',
    'Portugal': 'Portugal.csv',
    'Qatar': 'Qatar.csv',
    'Republic of Korea': 'Republic of Korea.csv',
    'Romania': 'Romania.csv',
    'Russian Federation': 'Russian Federation.csv',
    'Rwanda': 'Rwanda.csv',
    'Saint Lucia': 'Saint Lucia.csv',
    'Samoa': 'Samoa.csv',
    'Sao Tome and Principe ': 'Sao Tome and Principe .csv',
    'Saudi Arabia': 'Saudi Arabia.csv',
    'Senegal': 'Senegal.csv',
    'Serbia': 'Serbia.csv',
    'Seychelle': 'Seychelles.csv',
    'Sierra Leone': 'Sierra Leone.csv',
    'Singapore': 'Singapore.csv',
    'Slovakia': 'Slovakia.csv',
    'Slovenia': 'Slovenia.csv',
    'Solomon Island': 'Solomon Islands.csv',
    'South Africa': 'South Africa.csv',
    'Spain': 'Spain.csv',
    'Sri Lanka': 'Sri Lanka.csv',
    'Suriname': 'Suriname.csv',
    'Sweden': 'Sweden.csv',
    'Switzerland': 'Switzerland.csv',
    'Syrian Arab Republi': 'Syrian Arab Republic.csv',
    'Taiwan': 'Taiwan.csv',
    'Tajikistan': 'Tajikistan.csv',
    'Macedonia': 'TFYR of Macedonia.csv',
    'Thailand': 'Thailand.csv',
    'Timor-Leste': 'Timor-Leste.csv',
    'Tonga': 'Tonga.csv',
    'Tunisia': 'Tunisia.csv',
    'Turkey': 'Turkey.csv',
    'Uganda': 'Uganda.csv',
    'Ukraine': 'Ukraine.csv',
    'United Arab Emirate': 'United Arab Emirates.csv',
    'United Kingdom of Great Britain': 'United Kingdom of Great Britain.csv',
    'Tanzania': 'United Republic of Tanzania.csv',
    'United States of America': 'United States of America.csv',
    'Uruguay': 'Uruguay.csv',
    'Uzbekistan': 'Uzbekistan.csv',
    'Vanuatu': 'Vanuatu.csv',
    'Venezuela': 'Venezuela (Bolivarian Republic).csv',
    'Vietnam': 'Vietnam.csv',
    'Yemen': 'Yemen.csv',
    'Zambia': 'Zambia.csv',
    'Zimbabwe': 'Zimbabwe.csv'
}
