name: Python CI/CD DEV
# Unit/function/acceptance tests to be added 
on:
  push:
    branches:
      - dev

env:
  AZURE_WEBAPP_NAME: ai4good-dev 
  AZURE_WEBAPP_PACKAGE_PATH: '.' 

jobs:
  build:
    name: Deploy to DEV Azure Web App
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        ref: dev

    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7    
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U wheel setuptools
        sudo apt-get install -y gcc
        sudo apt-get install -y build-essential libssl-dev libffi-dev python3.6-dev
        sudo apt-get install -y python-numba python3-dask
        pip install -r requirements.txt

    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest ./ai4good --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests

    - name: Building web app
      uses: azure/appservice-build@v2-beta

    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_DEV_CREDENTIALS }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
