name: Python CI/CD DEV
# Unit/function/acceptance tests to be added 
on:
  push:
    branches:
      - dev

env:
  AZURE_WEBAPP_NAME: ai4good-dev 
  AZURE_WEBAPP_PACKAGE_PATH: '.' 

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        ref: dev

    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8    
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install -y gcc
        pip install wheel
        pip install -r requirements.txt

    - name: Building web app
      uses: azure/appservice-build@v2-beta

    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_DEV_CREDENTIALS }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
