name: AIforGood ModelServer push workflow

on: [pull_request]

jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Set up dependancies
        run: |
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          pip install pytest
          pytest
