name: Python CI/CD UAT
# Unit/function/acceptance tests to be added 
on:
  push:
    branches:
      - uat  

env:
  AZURE_WEBAPP_NAME: ai4good-uat  
  AZURE_WEBAPP_PACKAGE_PATH: '.' 

jobs:
  build:
    name: Deploy to UAT Azure Web App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: uat

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install -y gcc
        pip install -r requirements.txt

    - name: Building web app
      uses: azure/appservice-build@v2-beta

    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_UAT_CREDENTIALS }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  runwebtest:
    name: Web Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
        ref: uat

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
        
      - name: Set up dependancies
        run: |
          pip install -r requirements.txt
          pip install selenium        

      - name: Run acceptance tests
        run: |
          python ai4good/webapp/tests/dev_web_tests.py --zaluser ${{ secrets.ZALUSER }} --zalpassword ${{ secrets.ZALPASSWORD }} --zalhost ${{ secrets.ZALHOST }}