name: AIforGood ModelServer Web Test Workflow

on: [push]

jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
        
      - name: Set up dependancies
        run: |
          pip install -r requirements.txt
          pip install selenium        

      - name: Run acceptance tests
        run: |
          python ai4good/webapp/tests/dev_web_tests.py --zaluser ${{ secrets.ZALUSER }} --zalpassword ${{ secrets.ZALPASSWORD }} --zalhost ${{ secrets.ZALHOST }}
